apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-demo-consumer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vaccination-demo-consumer
  template:
    metadata:
      labels:
        app: vaccination-demo-consumer
    spec:
      containers:
        - image: localhost:5000/vaccination-demo
          command: [ "/bin/bash","-c" ]
          args: [ "./consumer_registration" ]
          name: consumer-registration
          volumeMounts:
            - name: vaccination-demo-config
              mountPath: /opt/vaccination-demo-consumer/.env
              subPath: .env
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: vaccination-demo-config
          configMap:
            name: vaccination-demo-config
