apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccination-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccination-demo
  template:
    metadata:
      labels:
        app: vaccination-demo
    spec:
      containers:
        - image: localhost:5000/vaccination-demo
          command: [ "/bin/bash","-c" ]
          args: [ "./api" ]
          name: consumer-registration
          volumeMounts:
            - name: vaccination-demo-config
              mountPath: /opt/vaccination-demo/.env
              subPath: .env
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: vaccination-demo-config
          configMap:
            name: vaccination-demo-config
---
apiVersion: v1
kind: Service
metadata:
  name: vaccination-demo
spec:
  selector:
    app: vaccination-demo
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 38000
